
- name: Get the EIP from the local file config
  shell: cat /var/tmp/eip.txt
  register: eips_dedicated

- name: Debug local EIP from file
  debug: msg={{ item }}
  with_items:
  - "{{ eips_dedicated.stdout_lines }}"

- name: Debug Instance meta-data public-ipv4
  debug: msg="{{ ansible_ec2_public_ipv4 }}"

- name: Checks if the public-ipv4 matches IPs in the list
  fail: msg="{{ ansible_ec2_public_ipv4 }} not in the list"
  when:
  - ansible_ec2_public_ipv4 not in eips_dedicated.stdout_lines
  register: eip_present
  ignore_errors: true

- name: Random pick of IP assignment
  ec2_eip: public_ip="{{ item }}" instance_id="{{ ansible_ec2_instance_id }}"  ec2_url="{{ ec2_url }}"
  with_items:
  - "{{ eips_dedicated.stdout_lines|random }}"
  when:
  - eip_present|failed
