# -

- name: Install required packages
  yum: name=python-netaddr state=latest

- name: Get the instance EC2 info
  action: ec2_facts
  register: ec2_data

- name: Check on EIP
  include: eip_checkup.yml

- name: Configure HAProxy
  include: elb_haproxy.yml
