
- name: Resolve ELB DNS name A records
  shell: dig {{ elb_dns_name }} | grep IN | grep A | grep -v \; | awk '{print $5}' | sort
  register: elbs_addresses

- name: Debug A records
  debug: msg={{ elbs_addresses.stdout }}

- name: Update the HAproxy configuration file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
